{
 "title": "Kafka Monitoring",
 "tags": [
  "kafka",
  "monitoring",
  "micrometer"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Records Processats per Client Group",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "sum by (client_group) (label_replace(kafka_consumer_fetch_manager_records_consumed_total, \"client_group\", \"$1\", \"client_id\", \"(.*)-\\\\d+$\"))",
     "legendFormat": "{{client_group}}"
    }
   ]
  },
  {
   "title": "Records Processats per Segon (Rate) per Client Group",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "sum by (client_group) (label_replace(kafka_consumer_fetch_manager_records_consumed_rate, \"client_group\", \"$1\", \"client_id\", \"(.*)-\\\\d+$\"))",
     "legendFormat": "{{client_group}}"
    }
   ]
  },
  {
   "title": "Bytes Processats Totals per Client Group",
   "type": "stat",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "sum by (client_group) (label_replace(kafka_consumer_fetch_manager_bytes_consumed_total, \"client_group\", \"$1\", \"client_id\", \"(.*)-\\\\d+$\"))",
     "legendFormat": "{{client_group}}"
    }
   ]
  },
  {
   "title": "Bytes Processats per Segon (Rate) per Client Group",
   "type": "stat",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "sum by (client_group) (label_replace(kafka_consumer_fetch_manager_bytes_consumed_rate, \"client_group\", \"$1\", \"client_id\", \"(.*)-\\\\d+$\"))",
     "legendFormat": "{{client_group}}"
    }
   ]
  },
  {
   "title": "Records Pendents (Max Lag) per Client Group",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 18, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "max by (client_group) (label_replace(kafka_consumer_fetch_manager_records_lag_max, \"client_group\", \"$1\", \"client_id\", \"(.*)-\\\\d+$\"))",
     "legendFormat": "{{client_group}}"
    }
   ]
  },
  {
   "title": "Errors per Listener",
   "type": "stat",
   "gridPos": { "x": 12, "y": 18, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "sum by (listener) (kafka_consumer_exceptions_total)",
     "legendFormat": "{{listener}}"
    }
   ]
  }
 ]
}