@startuml
!theme plain
skinparam sequenceMessageAlign center
skinparam shadowing false

title **Event Flow**

actor User #LightBlue
participant "**Booking Service**" as booking #APPLICATION
participant "**Orchestrator Service**" as orchestrator #LightGreen
participant "**Product Service**" as product #Orange
participant "**Payment Service**" as payment #Pink

== 1. Initiation ==
User -> booking : **POST** /bookings
booking -> booking : **[ES]** Append: BookingCreatedEvent
booking -> orchestrator : <font color=blue>**BOOKING_CREATED**</font>

== 2. Inventory Phase ==
orchestrator -> orchestrator : **[ES]** Append: Created
loop for each product
    orchestrator -> product : <font color=blue>**SAGA_REQUEST_STOCK**</font>
    alt #HoneyDew Stock Available
        product -> product : **[ES]** Append: ProductReservedEvent
        product -> orchestrator : <font color=green>**PRODUCT_RESERVED**</font>
        orchestrator -> orchestrator : **[ES]** Append: ProductReserved
    else #LavenderBlush Out of Stock
        product -> orchestrator : <font color=red>**PRODUCT_RESERVATION_FAILED**</font>
        orchestrator -> orchestrator : **[ES]** Append: ProductReservationFailed
        loop #khaki for each reserved product
            orchestrator -> orchestrator : **[ES]** Append: CompensatedProduct
            orchestrator -> product : <font color=orange>**SAGA_RELEASE_STOCK**</font>
            product -> product : **[ES]** Append: ProductReleasedEvent
        end
        orchestrator -> booking : <font color=red>**SAGA_CANCEL_BOOKING**</font>
        booking -> booking : **[ES]** Append: BookingFailedEvent
    end
end

== 3. Payment Phase ==
    orchestrator -> payment : <font color=blue>**SAGA_REQUEST_PAYMENT**</font>
    payment -> payment : **[ES]** Append: Initiated\nInternal: **PAYMENT_INITIATED**

    alt #HoneyDew Payment Success
        payment -> payment : **[ES]** Append: Completed
        payment -> orchestrator : <font color=green>**PAYMENT_COMPLETED**</font>
        orchestrator -> orchestrator : **[ES]** Append: PaymentCompleted

    else #LavenderBlush Payment Failed
        payment -> payment : **[ES]** Append: Failed
        payment -> orchestrator : <font color=red>**PAYMENT_FAILED**</font>
        orchestrator -> orchestrator : **[ES]** Append: PaymentFailed
    end


== 4. Finalization ==
alt #HoneyDew Payment Success
    orchestrator -> booking : <font color=green>**SAGA_CONFIRM_BOOKING**</font>
    booking -> booking : **[ES]** Append: BookingConfirmedEvent
else #LavenderBlush Payment Failed
    loop #khaki for each reserved product
        orchestrator -> orchestrator : **[ES]** Append: CompensatedProduct
        orchestrator -> product : <font color=orange>**SAGA_RELEASE_STOCK**</font>
        product -> product : **[ES]** Append: ProductReleasedEvent
    end
    orchestrator -> booking : <font color=red>**SAGA_CANCEL_BOOKING**</font>
    booking -> booking : **[ES]** Append: BookingFailedEvent
end

@enduml