openapi: 3.0.3
info:
  title: Booking Service API
  version: 1.0.0
paths:
  /bookings/{bookingId}:
    get:
      operationId: getBookingById
      summary: Get booking by ID
      parameters:
        - name: bookingId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Booking retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingRetrievedResponse'
  /bookings:
    post:
      operationId: createBooking
      summary: Create a new booking
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBookingRequest'
      responses:
        '201':
          description: Booking request created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookingResponse'

components:
  schemas:
    CreateBookingRequest:
      type: object
      properties:
        userId:
          type: string
          format: uuid
        products:
          type: array
          items:
            $ref: '#/components/schemas/BookingProduct'
      required:
        - userId
        - products

    BookingResponse:
      type: object
      properties:
        bookingId:
          type: string
          format: uuid
        status:
          type: string
          enum: [CREATED, CANCELLED, CONFIRMED]

    BookingRetrievedResponse:
      type: object
      properties:
        bookingId:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        status:
          type: string
        totalPrice:
          type: number
          format: double

    BookingProduct:
      type: object
      properties:
        productId:
          type: string
          format: uuid
        quantity:
          type: integer
          minimum: 1
      required:
        - productId
        - quantity

    Product:
      type: object
      properties:
        productId:
          type: string
          format: uuid
        quantity:
          type: integer
        price:
          type: number
          format: double

